# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US
tone_instructions: "Be constructive and helpful. Focus on code quality, security, and best practices."

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  path_instructions:
    - path: "client/**/*.tsx"
      instructions: |
        Review for React best practices:
        - Proper hook usage
        - Component composition
        - TypeScript types
        - Accessibility

    - path: "client/**/*.ts"
      instructions: |
        Review for TypeScript best practices:
        - Type safety (no any)
        - Proper error handling
        - Clean code patterns

    - path: "server/**/*.ts"
      instructions: |
        Review for Express/Node.js best practices:
        - Security (input validation, SQL injection)
        - Error handling
        - API design

    - path: "**/*.test.{ts,tsx}"
      instructions: |
        Review test quality:
        - Meaningful assertions
        - Edge cases covered
        - Test isolation

path_filters:
  exclude:
    - "**/*.lock"
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/coverage/**"
    - "**/*.min.js"

chat:
  auto_reply: true
