# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: 85%
        threshold: 5%

flags:
  client:
    paths:
      - client/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/test/**"
  - "**/mocks/**"
  - "**/*.d.ts"
